### PR TITLE
Modernized (again 😇)

### PR DESCRIPTION
**Pull request by voltechs**
- Modernized the gem
  - Ruby 2.3+ (cleans up some code, like `itself`, HEREDOCs, and named arguments)
- Added specs for 98% coverage (I'm tired 😫)
- requires gems instead of requiring files in the `DRb` proxy
- Breaks the interface, but sets up for a more powerful extension later, like calling out to a password program (`-A`) and choosing whether to load dependencies or not.
  - `initialize(ruby_opts: '', load_gems: true, password: nil)`
- Will need to modify the badges in the `README.md` to point at https://github.com/gderosa/rubysu
- Should consider not polluting `Kernel` with `wait_for` and place on `Sudo` module instead (or some other module

Bonus:
- Currently get's an A in [maintainability, and code coverage](https://codeclimate.com/github/TwilightCoders/rubysu).

### CODE REVIEW

**Comment by gderosa** [comment]
@voltechs, this is massive contribution, thanks!

Breaking some compatibility is fine, as you note in the [Issue comment](https://github.com/gderosa/rubysu/issues/2#issuecomment-435224076), it's still version zero. Plus, to my knowledge, no production code is depending on this so far... However, it's important that everything is reflected in the README: is the `initialize()`-related one the only API breaking change? In any case, please mention in the README all accepted parameters, which ones are mandatory, which ones have defaults etc.. My understanding is that this affects how users call `Sudo::Wrapper.new` and `Sudo::Wrapper.run`? (anything else?).

**Review by gderosa — CHANGES_REQUESTED** [review]
(See my comment about README and API changes).

**Comment by gderosa** [comment]
@voltechs:
> Will need to modify the badges in the README.md to point at https://github.com/gderosa/rubysu

I will also update (_after_ this is merged and when the new version is on rubygems.org) the Changelog, removing the "Unreleased", I will also add a section or file to credit you and others who have contributed in various ways. It's the least I could do :blush: . Also, creating a GitHub org "rubysu" may be a good idea, where we are both admins, and others can possibly join in the future.

**Comment by voltechs** [comment]
@gderosa I've updated the readme as you requested. Thanks for offering to credit me—I'd love that. GitHub orgs named the same as the gem feel unnecessary.

I don't think it's inappropriate to keep it under your name, but I sympathize, that's why I created [TwilightCoders](https://github.com/TwilightCoders) for all the open source work authored by myself and my friends/colleagues as they desire (that's not a proposition, but we can talk about it if you're interested). 

I think it's not a bad idea to add some collaborators here on GitHub and RubyGems, as you see fit and trust accordingly. Frankly we're lucky that 6 years later you were still around and engaged enough to maintain this 😄 so many OSS authors disappear (just go dig through the graveyard of RubyGems lol).

Let me know if I missed anything. 🍻

**Comment by voltechs** [comment]
~Hold up on merging this in. I am running into an issue when loading it directly into a project. I'll investigate.~

Edit: My bad—turns out I was trying to run a File block in the DRb. Turns out, code like this will not work, [which makes sense](https://ruby-doc.org/stdlib-2.4.0/libdoc/drb/rdoc/DRb.html), but is also a bummer.
```ruby
Sudo::Wrapper.run do |sudo|
  sudo[File].open("/etc/hosts", File::RDWR|File::CREAT) do |file|
    #... do something with the file.
  end
end
```

The alternative is:
```ruby
Sudo::Wrapper.run do |sudo|
  file = sudo[File].open("/etc/hosts", File::RDWR|File::CREAT)
  #... do something with the file.
  file.close
end
```

**Comment by gderosa** [comment]
@voltechs, thanks for the feedback about the organizational side of things, I'll think about all this.

Let me know when you've fixed the last issue and then I'm happy to merge.

Just to be clear: I don't have time to do any in-depth testing (let alone coding) so I'm just doing an high-level review here, but that should be enough, given all sorts of modern best-practices put in place - compared to my initial naive-ish  implementation 😛

**Comment by gderosa** [comment]
@voltechs , so it's not an issue at all? Great! And I agree with you that the "natural" limitation actually sucks (and doesn't satisfy the Principle Of Least Astonishment...).

But we will see in the future if we can overcome that...

This being said, I'm not sure I see the commit where you update the README?

**Comment by gderosa** [comment]
And since you're here... it would be great to have a "Caveats" section (or whatever) in the README where you explain the above limitation with file blocks... I think from a user perspective that would be appreciated a lot. Sorry for for being a bit obsessed with this but... you know 😉

**Comment by voltechs** [comment]
> @voltechs , so it's not an issue at all? Great! And I agree with you that the "natural" limitation actually sucks (and doesn't satisfy the Principle Of Least Astonishment...).
> 
> But we will see in the future if we can overcome that...

Agreed. My initial thoughts (for another time) is to try reading and executing the source of the block that is passed in. Or rather, passing the source of the block instead to the proxy method, then building a block in the DRb server and executing it.

> This being said, I'm not sure I see the commit where you update the README?

I needed to rewrite the history since I accidentally made some commits with a work email address. Also, I'm a fan of squashing/organizing commits for a meaningful git-history before it hits `master` ([so that's what I did](
https://github.com/gderosa/rubysu/pull/4/commits/b8ebcebb501f2d74664899c986363c2075192101#diff-04c6e90faac2675aa89e2176d2eec7d8R73)).

**Comment by gderosa** [comment]
Great!

So, to summarize, the breaking changes in the API are essentially the `load_gems` and `ruby_opts` options... correct?

They both have sensible defaults so existing code will still run...

And, therefore, the API changes aren't really breaking any backwards compatibility - which is even better.

Am I understanding correctly?

**Comment by voltechs** [comment]
> Great!
> 
> So, to summarize, the breaking changes in the API are essentially the `load_gems` and `ruby_opts` options... correct?
> 
> They both have sensible defaults so existing code will still run...
> 
> And, therefore, the API changes aren't really breaking any backwards compatibility - which is even better.
> 
> Am I understanding correctly?

It technically breaks the API because to pass `ruby_opts`, you now say `Sudo::Wrapper.run(ruby_opts: 'whatever')` versus `Sudo::Wrapper.run('whatever')`. (Named arguments)

**Comment by gderosa** [comment]
Ah, right. So it's only compatible if one calls with no arguments at all... but it's okay since you documented it.

**Pull request merged**
